App\Dto\Response\Planet\DtoResponsePlanet:
    attributes:
        id:
            groups: ['DtoResponsePlanet']
        name:
            groups: ['DtoResponsePlanet']
        rotation_period:
            groups: ['DtoResponsePlanet']
        orbital_period:
            groups: ['DtoResponsePlanet']
        diameter:
            groups: ['DtoResponsePlanet']
        films_count:
            groups: ['DtoResponsePlanet']
        created:
            groups: ['DtoResponsePlanet']
        edited:
            groups: ['DtoResponsePlanet']
        url:
            groups: ['DtoResponsePlanet']